# -*- coding: utf-8 -*-
"""fyp_data_visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLx_8471-CzTG1Zjo6TMXVlnsPOCtRs3
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### Helper Functions"""

def get_audio_file_features_data(base_path, model_name, audio_model_files):
    for file in os.listdir(base_path):
        if file.endswith('.csv') and '_features' in file and model_name == file.split('_')[0]:
            feature_type = '_'.join(file.split('_')[1:-1]) # file convention is {model_name}_{dataname...}_{data}
            df = pd.read_csv(os.path.join(base_path, file))
            # df['file_id'] = df['filename'].str.split('_', n=1).str[1].replace('.wav', '', regex=True)
            audio_model_files[model_name][feature_type] = df

    return audio_model_files

"""### Load features extracted from audio files"""
generation_outputs_dir = '/home/kian/fyp-final/FYP/data/audio_files'
audio_features_dir = '/home/kian/fyp-final/FYP/data/features'
audio_model_files = {}

for model_name in os.listdir(generation_outputs_dir):
    audio_model_files[model_name] = {}
    audio_features_path = 'FYP/data/features/Suno-V5_features.csv'
    model_audio_path = os.path.join(generation_outputs_dir, model_name)
    audio_model_files = get_audio_file_features_data(audio_features_dir, model_name, audio_model_files)

"""### Load master prompts to get the target values and join with target"""

master_prompts = '/home/kian/fyp-final/FYP/config/prompt_tasks/master_prompts_v2.csv'
master_prompts_json = '/home/kian/fyp-final/FYP/config/prompt_tasks/prompts.json'

# target_df = pd.read_csv(master_prompts)
target_df = pd.read_json(master_prompts_json)
target_df = target_df.rename(columns={"filename": "file_id"})

for model_name in audio_model_files:
    current_model_df = target_df.copy()
    for feature_type in audio_model_files[model_name]:
        if feature_type not in ['dataframe']:
            feature_df = audio_model_files[model_name][feature_type]
            # prefixed_df = feature_df.add_prefix(f"{feature_type}_")
            # prefixed_df = prefixed_df.rename(columns={f"{feature_type}_file_id": "file_id"})
            current_model_df = current_model_df.merge(feature_df, how='left', on="file_id")

    audio_model_files[model_name]['dataframe'] = current_model_df

"""### Process tasks

Here we are iterating over the tasks for each model, and extracting the features we need

"""

# the tasks are tempo, key, scale, tempo change, key modulation, time signature
import pandas as pd

for audio_model in audio_model_files:
    audio_model_df = audio_model_files[audio_model]['dataframe']
    processed_tasks = {}

    split_dfs = {task: group.copy() for task, group in audio_model_df.groupby('task')}

    for task, task_df in split_dfs.items():
        # print(task_df.columns)
        if task == 'tempo':
            bpm_cols = [c for c in task_df.columns if '_bpm' in c]

            for col in bpm_cols:
                measured = pd.to_numeric(task_df[col], errors='coerce')
                target = pd.to_numeric(task_df['target'], errors='coerce')

                task_df[f'{col}_abs_error'] = (measured - target).abs()
                task_df[f'{col}_signed_error'] = measured - target

                print(col)

                task_df[f'{col}_tempo_bias'] = task_df[f'{col}_signed_error'].apply(
                    lambda x: 'overshoot' if x > 0.5 else ('undershoot' if x < -0.5 else 'perfect')
                )

        processed_tasks[task] = task_df

    audio_model_files[audio_model]['proccessed_tasks'] = processed_tasks

"""## Scatter Plots for Target vs Actual BPM"""

for model_name, model_data in audio_model_files.items():
    tempo_df = model_data['proccessed_tasks']['tempo'].copy()
    tempo_df['target'] = pd.to_numeric(tempo_df['target'], errors='coerce')

    plt.figure(figsize=(14, 6))

    # Diagonal line
    min_bpm = min(tempo_df['target'].min(), tempo_df['bpm_essentia'].min(), tempo_df['bpm_librosa'].min())
    max_bpm = max(tempo_df['target'].max(), tempo_df['bpm_essentia'].max(), tempo_df['bpm_librosa'].max())
    diagonal_line = [min_bpm, max_bpm]

    # Essentia BPM plotting
    plt.subplot(1, 2, 1)
    sns.scatterplot(data=tempo_df, x='target', y='bpm_essentia', hue='genre', palette='viridis')
    plt.plot(diagonal_line, diagonal_line, color='red', linestyle='--', label='Perfect Prediction')
    plt.title(f'{model_name} Target vs Essentia BPM by Genre')
    plt.xlabel('Target BPM')
    plt.ylabel('Essentia BPM')
    plt.legend()
    plt.grid(True, linestyle=':', alpha=0.7)

    # Librosa BPM plotting
    plt.subplot(1, 2, 2)
    sns.scatterplot(data=tempo_df, x='target', y='bpm_librosa', hue='genre', palette='viridis')
    plt.plot(diagonal_line, diagonal_line, color='red', linestyle='--', label='Perfect Prediction')
    plt.title(f'{model_name} Target vs Librosa BPM by Genre')
    plt.xlabel('Target BPM')
    plt.ylabel('Librosa BPM')
    plt.legend()
    plt.grid(True, linestyle=':', alpha=0.7)

    plt.tight_layout()
    plt.show()

"""## Box Plots for Absolute BPM Error by Genre

This shows a box plot for the difference between the target BPM and the measured BPM
"""

for model_name, model_data in audio_model_files.items():
    tempo_df = model_data['proccessed_tasks']['tempo'].copy()
    tempo_df['target'] = pd.to_numeric(tempo_df['target'], errors='coerce')

    plt.figure(figsize=(14, 6))

    # Box plot for Essentia BPM absolute errors by genre
    plt.subplot(1, 2, 1)
    sns.boxplot(data=tempo_df, x='genre', y='bpm_essentia_abs_error', hue='genre', palette='viridis', legend=False)
    plt.title('Essentia BPM Absolute Error by Genre')
    plt.xlabel('Genre')
    plt.ylabel('Absolute Error (BPM)')
    plt.grid(True, linestyle=':', alpha=0.7)

    # Box plot for Librosa BPM absolute errors by genre
    plt.subplot(1, 2, 2)
    sns.boxplot(data=tempo_df, x='genre', y='bpm_librosa_abs_error', hue='genre', palette='viridis', legend=False)
    plt.title('Librosa BPM Absolute Error by Genre')
    plt.xlabel('Genre')
    plt.ylabel('Absolute Error (BPM)')
    plt.grid(True, linestyle=':', alpha=0.7)

    plt.tight_layout()
    plt.show()

"""### Bar Chart for key"""

for model_name, model_data in audio_model_files.items():
    key_df = model_data['proccessed_tasks']['key'].copy()

    key_df['target_root'] = key_df['target'].str.split(' ').str[0]
    key_df['is_correct'] = (key_df['target_root'].str.strip() == key_df['key'].str.strip()).astype(int)

    plt.figure(figsize=(10, 5))
    sns.barplot(data=key_df, x='genre', y='is_correct', palette='magma', errorbar=None)

    plt.title(f'{model_name} Essentia Key Detection Accuracy (%) by Genre')
    plt.ylabel('Accuracy (1.0 = 100%)')
    # plt.axhline(0.5, color='red', linestyle='--', alpha=0.5) # Benchmark line
    plt.show()